name: CI-CD

on: 
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main
  workflow_dispatch:

env:
  AZURE_RG: rg-peterdemo20251203
  AZURE_SUBSCRIPTION: cd8acfc4-baea-4c96-8ae2-f6b5fc55eda8
  AZURE_LOCATION: swedencentral

jobs:
  Build-Job:
    runs-on: ubuntu-latest
    env:
      configuration: release
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v6
    - name: Restore NuGet Package
      run: dotnet restore
    - name: Build Project
      run: dotnet build --no-restore --configuration ${{ env.configuration }}
    - name: Publish
      run: dotnet publish ./WebApplication1 --configuration ${{ env.configuration }} --output ${{ runner.temp }}/publish
    - name: Upload publish artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: publish_artifact
        path: ${{ runner.temp }}/publish
        retention-days: 30
    - name: Upload a Templates Artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: templates_artifact
        path: ./templates/* 
        retention-days: 30
  RG-Job:
    runs-on: ubuntu-latest
    needs: [Build-Job]
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create Resource Group
        uses: Azure/cli@v1
        with:
          inlineScript: 
            az group create --name ${{ env.AZURE_RG }} --location ${{ env.AZURE_LOCATION }}
          
  Dev-Job:
    runs-on: ubuntu-latest
    needs: [ RG-Job ]
    env:
      AZURE_WEBAPP_NAME: www-demopeter20251203d
    steps:
      - name: Download templates
        uses: actions/download-artifact@v4
        with:
          name: templates_artifact
          path: ${{ runner.temp }}/templates
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy BICEP template
        uses: azure/arm-deploy@v1
        id: deploywebappd
        with:
          deploymentName: create-webapp-dev
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.AZURE_RG }}
          template: ${{ runner.temp }}/templates/webapp.bicep
          parameters: location=${{ env.AZURE_LOCATION }} appName=${{ env.AZURE_WEBAPP_NAME }}

      - name: Deploy Web Publish Artifact
        uses: actions/download-artifact@v4
        with:
          name: templates_artifact
          path: ${{ runner.temp }}/publish
      - name: Deploy Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ runner.temp }}/publish

          
    
    
