name: CI-CD

on: 
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main
  workflow_dispatch:

env:
  AZURE_RG: rg-peterdemo20251203
  AZURE_SUBSCRIPTION: cd8acfc4-baea-4c96-8ae2-f6b5fc55eda8
  AZURE_LOCATION: swedencentral

jobs:
  Build-Job:
    runs-on: ubuntu-latest
    env:
      configuration: release
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v6
    - name: Restore NuGet Package
      run: dotnet restore
    - name: Build Project
      run: dotnet build --no-restore --configuration ${{ env.configuration }}
    - name: Publish
      run: dotnet publish --configuration ${{ env.configuration }} --output ${{ runner.temp }}
    - name: Upload publish artifact
      uses: action/upload-artifact@v3.0.0
      with:
        name: publish_artifact
        path: ${{ runner.temp }}/publish
        retention-days: 30
        

          
      
    
